name: Merge
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:
    inputs:
      pr_number:
        type: string
        required: true
run-name: |
  ${{ github.event_name }}
   - PR ${{
    inputs.pr_number
    || github.event.workflow_run.pull_requests[0].number
    || github.event.pull_request.number
    || 'Unknown'
  }}
   - workflow event: ${{ github.event.workflow_run.event || 'N/A' }}
jobs:
  log:
    name: Log
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
  merge:
    name: Merge
    if: |
      (
        github.event_name == 'workflow_dispatch'
      )
      ||
      (
        github.event_name == 'workflow_run'
        && github.event.workflow_run.conclusion == 'success'
        && github.event.workflow_run.event == 'pull_request'
        && startsWith(github.event.workflow_run.pull_requests[0].base.ref, 'ma')
      )
      ||
      (
        github.event_name == 'pull_request_review'
        && github.event.review.state == 'approved'
        && startsWith(github.event.pull_request.base.ref, 'ma')
      )
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo merging PR ${{
            inputs.pr_number
            || github.event.workflow_run.pull_requests[0].number
            || github.event.pull_request.number 
          }}