name: Merge
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
run-name: |
  ${{ github.event.workflow.name }}
   - ${{ github.event.workflow_run.event }}
   - ${{ github.event.workflow_run.conclusion }}
   - ${{ github.event.workflow_run.pull_requests[0].number }}
jobs:
  merge:
    name: Merge
    if: |
      github.event.workflow_run.event == 'pull_request'
      && github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo merging
      - run: echo '${{ github.event.workflow_run.pull_requests[0].number }}'
      - run: echo '${{ toJSON(github.event.workflow_run) }}'
