name: Merge
on:
  workflow_run:
    workflows:
      - 'Test'
      - 'PR Review'
    types:
      - completed
  workflow_dispatch:
    inputs:
      pr_number:
        type: string
        required: true
run-name: >
  ${{ github.event_name }}
   - PR ${{ inputs.pr_number || github.event.workflow_run.pull_requests[0].number || 'unknown' }}
   - workflow.name: ${{ github.event.workflow.name || 'N/A' }}
   - workflow_run.event: ${{ github.event.workflow_run.event || 'N/A' }}
jobs:
  log:
    name: Log
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
  merge:
    name: Merge
    if: |
      (
        github.event_name == 'workflow_dispatch'
      )
      ||
      (
        github.event_name == 'workflow_run'
        && github.event.workflow.name == 'Test'
        && github.event.workflow_run.event == 'pull_request'
        && github.event.workflow_run.conclusion == 'success'
        && startsWith(github.event.workflow_run.pull_requests[0].base.ref, 'ma')
      )
      ||
      (
        github.event_name == 'workflow_run'
        && github.event.workflow.name == 'PR Review'
        && github.event.workflow_run.event == 'pull_request_review'
        && github.event.workflow_run.conclusion == 'success'
        && startsWith(github.event.workflow_run.pull_requests[0].base.ref, 'ma')
      )
    runs-on: ubuntu-latest
    steps:
      - run: >
          echo merging PR ${{
            inputs.pr_number || github.event.workflow_run.pull_requests[0].number
          }}
