name: PR Review
on:
  pull_request_review:
    types:
      - submitted
run-name: |
  PR ${{ github.event.pull_request.number }}
   - ${{ github.event.review.state }}
   - ${{ github.event.pull_request.base.ref }}
jobs:
  log:
    name: Log
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
  check:
    name: Check
    if: |
      github.event.review.state == 'commented'
      && startsWith(github.event.pull_request.base.ref, 'ma')
    runs-on: ubuntu-latest
    steps:
      - run: echo success
