name: Test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
jobs:
  Log:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Log
        run: echo env ${{ inputs.environment }} ACC ${{ vars.ACC }}
      - name: Install clang
        run: apt install clang
