name: Test
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
run-name: ${{ github.ref_name }} - ${{ github.head_ref }} - ${{ github.base_ref }}
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo testing
      - run: echo '${{ toJSON(github.event.pull_request) }}'
      - run: echo '${{ toJSON(github.event.push) }}'
      - run: echo '${{ toJSON(github) }}'