name: Test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
jobs:
  Debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: echo env ${{ inputs.environment }}
  Log:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Log
        run: echo hi $ACC
