name: Test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - staging
          - production
jobs:
  Log:
    runs-on: ubuntu-latest
    environment: ${{ format('deploy_{0}', inputs.environment) }}
    steps:
      - run: echo env ${{ inputs.environment }} ACC ${{ vars.ACC }}
      - run: sudo apt install clang
      - run: clang++ --version
