name: Test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
jobs:
  Log:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo env ${{ inputs.environment }} ACC ${{ vars.ACC }}
      - run: sudo apt install clang
      - run: clang++ --version
