name: Test
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
  push:
    branches:
      - main
run-name: ${{ github.ref_name }} - ${{ inputs.version }}
jobs:
  Log:
    runs-on: ubuntu-latest
    steps:
      - run: echo ref ${{ github.ref_name }} version ${{ inputs.version }} final ${{ inputs.version || github.ref_name }}
      - run: git --version
