name: Test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - staging
          - production
      version:
        type: string
        required: true
run-name: Deploy ${{ inputs.environment }} ${{ inputs.version }}
jobs:
  Log:
    runs-on: ubuntu-latest
    environment: ${{ format('deploy_{0}', inputs.environment) }}
    steps:
      - run: echo env ${{ inputs.environment }} ACC ${{ vars.ACC }}
      - run: sudo apt install gcc
      - run: g++ --version
